version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: keven_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: keven
      POSTGRES_PASSWORD: kevenpassword
      POSTGRES_DB: keven_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true